DROP TABLE IF EXISTS event_category CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS event_category (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(55) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(55) NOT NULL,
  email VARCHAR(55) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS compilation (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  events INT[],
  pinned BOOLEAN NOT NULL,
  title VARCHAR(55),
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000),
  category_id INT NOT NULL,
  confirmed_requests INT,
  created_on TIMESTAMP,
  description VARCHAR(7000),
  event_date TIMESTAMP NOT NULL,
  initiator INT NOT NULL,
  event_location DOUBLE PRECISION[] NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INT NOT NULL,
  published_on TIMESTAMP,
  request_moderation BOOLEAN,
  state VARCHAR(64),
  title VARCHAR(120) NOT NULL,
  views INT,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT fk_events_to_category FOREIGN KEY(category_id) REFERENCES event_category(id),
  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator) REFERENCES users(id)
);