DROP TABLE IF EXISTS event_category CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS event_compilations CASCADE;

CREATE TABLE IF NOT EXISTS event_category (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(55) NOT NULL,
  CONSTRAINT uq_category_name UNIQUE (name),
  CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000),
  category_id INT NOT NULL,
  confirmed_requests INT,
  created_on TIMESTAMP,
  description VARCHAR(7000),
  event_date TIMESTAMP NOT NULL,
  initiator_id INT NOT NULL,
  event_location DOUBLE PRECISION[] NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INT NOT NULL,
  published_on TIMESTAMP,
  request_moderation BOOLEAN,
  state VARCHAR(64),
  title VARCHAR(120) NOT NULL,
  CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT fk_events_to_category FOREIGN KEY(category_id) REFERENCES event_category(id),
  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS compilation (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN NOT NULL,
  title VARCHAR(55),
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id INT,
  requester_id INT,
  status VARCHAR(55),
  created TIMESTAMP,
  CONSTRAINT pk_participation PRIMARY KEY (id),
  CONSTRAINT fk_participation_to_users FOREIGN KEY(requester_id) REFERENCES users(id),
  CONSTRAINT fk_participation_to_event FOREIGN KEY(event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS event_compilations (
  compilation_id INT NOT NULL,
  event_id INT NOT NULL,
  PRIMARY KEY (compilation_id, event_id),
  CONSTRAINT fk_compilation_id_to_compilation FOREIGN KEY (compilation_id) REFERENCES compilation(id) ON DELETE CASCADE,
  CONSTRAINT fk_event_id_to_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);