services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: stats

  stats-server:
    build:
      context: ./stats-service/server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "7432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ewm-db