server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
#    локально
#    url: jdbc:postgresql://localhost:6432/stats
    url: jdbc:postgresql://stats-db:5432/stats
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass