
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:6432/stats
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass